// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chpjcjrmnoafquslnkjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNocGpjanJtbm9hZnF1c2xua2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMjk4MzIsImV4cCI6MjA1MTYwNTgzMn0.cWJ68QoQeVCS_c0XQy8wEgZb6nR_YAuWNLOmqRIGm4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);